### PR TITLE
Fix can't set attribute error

### LINKED ISSUE #22: Can't set attribute gnote.text
Steps to reproduce

1. create a keep note with an image
1. run kim.py to export it
1. line 211 throws an exception - gnote.text = blob_file + "\n" + gnote.text

Workaround

I had to change gnote.text to note_text and write that out.

### PR DESCRIPTION
**Pull request by davenicoll**
Resolves #22

### CODE REVIEW

**Comment by davenicoll** [comment]
I've also added a fix for certain unicode sequences and checkboxes not being replaced.

**Comment by djsudduth** [comment]
My apologies - I haven't created a contributor guide yet. Can you please fork the development branch and do the pull request there rather than the main branch? I have some code changes in already for 0.4.1.

**Comment by davenicoll** [comment]
No problem, done. Apologies, I didn't spot the develop branch when I created the PR.

**Comment by djsudduth** [comment]
Ah - sorry I didn't see that this merge was the other fix - my apologies @davenicoll !!!!

**Pull request closed without merging**
