### PR TITLE
Add google Takeout data dump support

### PR DESCRIPTION
**Pull request by drmikecrowe**
NOTE:  This is NOT ready for prime-time at all.  This is more an exploration of if you are interested.

I could not connect KIM to my account due to all the security I put in place.  So, I exported the data from Google Takeout, and sucked in the directory into Markdown.

I struggled with your formatting, so my `main` branch adds `yapf` and reformats your branch using it (no logic changes).  If you do that first, this PR looks better.

I *think* I have one Obsidian specific code in place:

```py
	          f.write(f"""---
	  updated: ["{str(gnote.timestamps.updated)}"]
	  created: ["{str(gnote.timestamps.created)}"]
	  ---    
	    
	  """)
```

I got tired of trying to make it generic and took a shortcut.  If you are interested in this branch, I can clean that up

### CODE REVIEW

**Comment by djsudduth** [comment]
I'll take a look - thanks for the pull!

**Comment by djsudduth** [comment]
Oh bummer - can you resubmit this against the dev branch and not main? I’m sorry, I really need to add a CONTRIBUTING guide.

**Comment by drmikecrowe** [comment]
Can you run `yapf` on `develop` (or choose which formatter you like) so this is easier?

**Comment by djsudduth** [comment]
@drmikecrowe - should I close this pull request and look only at your newer one?

**Pull request closed without merging**
